GET http://localhost:3333/tasks

###

POST http://localhost:3333/tasks
Content-Type: application/json

{
    "description": "Criar o Front-end da aplicação 'task-manager'."
}

###
PATCH http://localhost:3333/tasks/661429947f96f483dedfcdcf
Content-Type: application/json

{
    "is_completed": true
}

###
DELETE http://localhost:3333/tasks/661429517f96f483dedfcdce