GET http://localhost:3333/tasks

###

POST http://localhost:3333/tasks
Content-Type: application/json

{
    "description": "Executar os testes das requisições."
}

###
PATCH http://localhost:3333/tasks/661429947f96f483dedfcdcf
Content-Type: application/json

{
    "is_completed": true
}

###
DELETE http://localhost:3333/tasks/661429517f96f483dedfcdce